// <auto-generated />
using System;
using MaqolAppApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaqolAppApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221105101835_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MaqolAppApi.Models.Maqola", b =>
                {
                    b.Property<Guid>("MaqolaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Batafsil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KurishlarSoni")
                        .HasColumnType("int");

                    b.Property<Guid>("MuallifId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RasmUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sarlavha")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("YaratilganVaqti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("MaqolaId");

                    b.HasIndex("MuallifId");

                    b.ToTable("Maqolalar");
                });

            modelBuilder.Entity("MaqolAppApi.Models.Muallif", b =>
                {
                    b.Property<Guid>("MuallifId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Familya")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RasmUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TugilganKuni")
                        .HasColumnType("datetime2");

                    b.HasKey("MuallifId");

                    b.ToTable("Mualliflar");
                });

            modelBuilder.Entity("MaqolAppApi.Models.Maqola", b =>
                {
                    b.HasOne("MaqolAppApi.Models.Muallif", "Muallif")
                        .WithMany()
                        .HasForeignKey("MuallifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muallif");
                });
#pragma warning restore 612, 618
        }
    }
}
